#!/usr/bin/env node
'use strict';

// CLI: renders grouping stored procedures from a JSON data model.
// Usage: node generate.js <model.json> [--emit both|offset|cache] [--out file.sql]

const fs = require('fs');
const path = require('path');
const { parseModel } = require('./lib/model');
const { renderOffsetProc } = require('./lib/render-offset');
const { renderCache } = require('./lib/render-cache');

const USAGE = 'Usage: node generate.js <model.json> [--emit both|offset|cache] [--out file.sql]';

function parseArgs(argv) {
    const args = { _: [], emit: 'both', out: null, help: false };
    for (let i = 2; i < argv.length; i++) {
        const a = argv[i];
        if (a === '--out') args.out = argv[++i];
        else if (a === '--emit') args.emit = argv[++i];
        else if (a === '--help' || a === '-h') args.help = true;
        else args._.push(a);
    }
    return args;
}

function main() {
    const args = parseArgs(process.argv);
    if (args.help) {
        console.log(USAGE);
        return;
    }
    if (args._.length === 0) {
        console.error(USAGE);
        process.exit(1);
    }
    if (!['both', 'offset', 'cache'].includes(args.emit)) {
        console.error(`Error: invalid --emit '${args.emit}' (expected both|offset|cache).`);
        process.exit(1);
    }

    let model;
    try {
        const raw = JSON.parse(fs.readFileSync(args._[0], 'utf8'));
        model = parseModel(raw);
    } catch (e) {
        console.error('Error: ' + e.message);
        process.exit(1);
    }

    if ((args.emit === 'both' || args.emit === 'cache') && !model.cache) {
        console.error(`Error: --emit ${args.emit} requires a 'cache' config in the model.`);
        process.exit(1);
    }

    const parts = [
        `-- Generated by groupproc-gen from ${path.basename(args._[0])}. Do not edit by hand.`,
    ];
    if (args.emit === 'both' || args.emit === 'offset') parts.push(renderOffsetProc(model));
    if (args.emit === 'both' || args.emit === 'cache') parts.push(renderCache(model));
    const sql = parts.join('\n\n') + '\n';

    if (args.out) {
        fs.writeFileSync(args.out, sql);
        console.error(`Wrote ${args.out}`);
    } else {
        process.stdout.write(sql);
    }
}

main();
